// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeContainer: typeof import('./src/components/common/DarkModeContainer.vue')['default']
    DarkModeSwitch: typeof import('./src/components/common/DarkModeSwitch.vue')['default']
    HomeItem: typeof import('./src/components/HomeItem.vue')['default']
    HoverContainer: typeof import('./src/components/common/HoverContainer.vue')['default']
    'Icon:mdiMoonWaningCrescent': typeof import('~icons/mdi/moon-waning-crescent')['default']
    'Icon:mdiWhiteBalanceSunny': typeof import('~icons/mdi/white-balance-sunny')['default']
    IconLineMdMenuFoldLeft: typeof import('~icons/line-md/menu-fold-left')['default']
    IconLineMdMenuUnfoldLeft: typeof import('~icons/line-md/menu-unfold-left')['default']
    'IconMdi:accountChildCircle': typeof import('~icons/mdi/account-child-circle')['default']
    IconMdiDragHorizontal: typeof import('~icons/mdi/drag-horizontal')['default']
    IconMdiDragVertical: typeof import('~icons/mdi/drag-vertical')['default']
    'IconPh:airplaneTiltFill': typeof import('~icons/ph/airplane-tilt-fill')['default']
    MenuProvider: typeof import('./src/components/common/MenuProvider.vue')['default']
    NAffix: typeof import('naive-ui')['NAffix']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSpace: typeof import('naive-ui')['NSpace']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
