// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BasicModal: typeof import('./src/components/Modal/src/basicModal.vue')['default']
    DarkModeContainer: typeof import('./src/components/common/DarkModeContainer.vue')['default']
    DarkModeSwitch: typeof import('./src/components/common/DarkModeSwitch.vue')['default']
    HomeItem: typeof import('./src/components/HomeItem.vue')['default']
    HoverContainer: typeof import('./src/components/common/HoverContainer.vue')['default']
    'Icon:mdiMoonWaningCrescent': typeof import('~icons/mdi/moon-waning-crescent')['default']
    'Icon:mdiWhiteBalanceSunny': typeof import('~icons/mdi/white-balance-sunny')['default']
    IconCustomGateway: typeof import('~icons/custom/gateway')['default']
    IconLineMdMenuFoldLeft: typeof import('~icons/line-md/menu-fold-left')['default']
    IconLineMdMenuUnfoldLeft: typeof import('~icons/line-md/menu-unfold-left')['default']
    'IconMdi:accountChildCircle': typeof import('~icons/mdi/account-child-circle')['default']
    IconMdiDragHorizontal: typeof import('~icons/mdi/drag-horizontal')['default']
    IconMdiDragVertical: typeof import('~icons/mdi/drag-vertical')['default']
    MenuProvider: typeof import('./src/components/common/MenuProvider.vue')['default']
    NAffix: typeof import('naive-ui')['NAffix']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    NBreadcrumb: typeof import('naive-ui')['NBreadcrumb']
    NBreadcrumbItem: typeof import('naive-ui')['NBreadcrumbItem']
    NButton: typeof import('naive-ui')['NButton']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDivider: typeof import('naive-ui')['NDivider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NInput: typeof import('naive-ui')['NInput']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NResult: typeof import('naive-ui')['NResult']
    NScrollbar: typeof import('naive-ui')['NScrollbar']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NTooltip: typeof import('naive-ui')['NTooltip']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
