// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DarkModeContainer: typeof import('./src/components/common/DarkModeContainer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeItem: typeof import('./src/components/HomeItem.vue')['default']
    NAffix: typeof import('naive-ui')['NAffix']
    NaiveProvider: typeof import('./src/components/common/NaiveProvider.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NTag: typeof import('naive-ui')['NTag']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TestAuto: typeof import('./src/components/TestAuto.vue')['default']
  }
}

export {}
