version: '3'

services:
  gateway_admin_web_fe:
    image: image_dest_replace
    container_name: gateway_admin_web_v2
    restart: always
    ports:
      - 18088:8080
    environment:
      - TZ=Asia/Shangha
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./conf/config.json:/opt/www/config.json
